# https://docs.docker.com/compose/compose-file/compose-file-v2/
version: '2.1'
services:
  api:
    build: .
    ports:
      - 8000:8000
    command: python ./mysite/manage.py runserver 0.0.0.0:8000


