# Generated by Django 2.0.4 on 2019-03-13 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogtype',
            table='blog_type',
        ),
    ]
