# Generated by Django 2.0.4 on 2019-03-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190313_2355'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
    ]
