# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-21 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegCode',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=36)),
                ('reg_code', models.CharField(max_length=36)),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_reg_code',
            },
        ),
    ]
